### ISSUE TITLE
Update Pre-built Wheels

### ISSUE THREAD

**Issue by batuhanfaik** [teddykoker/torchsort#78]
### Problem
Building `torchsort` using conda as the package manager on AWS EC2 instances with CUDA toolkit 12.1+ is quite cumbersome.

### Possible Solution
It would be fantastic if we could update the pre-built wheels to support newer versions of CUDA.

Wheels for the following versions should be added:
```
python>=3.10
torch>=2.1
cuda>=12.0
```

I specifically require the following wheel file:
`torchsort-0.1.9+pt21cu121-cp311-cp311-linux_x86_64.whl`

#### Why?
As noted in the README, installing `gxx_linux-64` should not be required when using conda. Steps provided in #52 are also obsolete for CUDA v12+, since `cudatoolkit-dev` goes up to CUDA v11.7 (other methods mentioned in the same issue are also obsolete). One can obtain the latest `nvcc` from [`cuda-nvcc`](https://anaconda.org/nvidia/cuda-nvcc) if necessary. My attempts using `gxx_linux-64==9.5.0` and `cuda-nvcc==12.1.1` were successful. Below is my environment yaml file if anybody would like to reproduce.

```yaml
name: torchsort_p311
channels:
    - conda-forge
    - pytorch
    - nvidia
    - nvidia/label/cuda-12.1.1
dependencies:
    - python>=3.11
    - pytorch>=2
    - pytorch-cuda==12.1
    # I don't like this a single bit
    - cuda-nvcc
    - gxx_linux-64>=9.5,<10
    - pip
    - pip:
        - torchsort
```
